version: "3.9"

services:
  # ── Application ─────────────────────────────────────────────────────────────
  app:
    build:
      context: .
      target: runner
    ports:
      - "${PORT:-8000}:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://zorvyn:zorvyn_pass@db:5432/zorvyn_db
      REDIS_URL: redis://redis:6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - zorvyn-net

  # ── PostgreSQL ───────────────────────────────────────────────────────────────
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: zorvyn_db
      POSTGRES_USER: zorvyn
      POSTGRES_PASSWORD: zorvyn_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U zorvyn -d zorvyn_db" ]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    networks:
      - zorvyn-net

  # ── Redis ────────────────────────────────────────────────────────────────────
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped
    networks:
      - zorvyn-net

volumes:
  postgres_data:
  redis_data:


networks:
  zorvyn-net:
    driver: bridge
